"""Confluence & Strategy page — Week 10.

Renders the Week 7 strategy output: the ranked trade zones with their
confluence scores, the final decision, and the trade plan (Week 8).
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from dashboard.services import AnalysisBundle


def render(bundle: AnalysisBundle) -> None:
    """Render the confluence / strategy page for the loaded bundle."""
    st.title("Confluence & Strategy")
    st.caption(f"{bundle.symbol} · {bundle.timeframe}")

    strategy = bundle.strategy
    if strategy is None:
        st.info("No strategy data loaded.")
        return

    decision = strategy.decision
    if decision is not None:
        st.subheader("Decision")
        cols = st.columns(3)
        cols[0].metric("Status", str(getattr(decision.status, "value", decision.status)))
        cols[1].metric("Confidence", f"{decision.confidence:.1f}")
        cols[2].metric("Direction", str(getattr(decision.direction, "value", decision.direction)))
        if decision.reason:
            st.write(decision.reason)

    # --- ranked zones -----------------------------------------
    st.subheader("Trade Zones")
    zones = getattr(strategy, "zones", []) or []
    if zones:
        df = pd.DataFrame(
            [
                {
                    "Direction": str(getattr(z.direction, "value", z.direction)),
                    "Entry": z.entry_price,
                    "Stop": z.stop_loss,
                    "Target": z.target,
                    "Confluence": z.confluence_score,
                    "R:R": z.risk_reward_ratio,
                    "Status": str(getattr(z.status, "value", z.status)),
                    "Reason": z.reason,
                }
                for z in zones
            ]
        )
        st.dataframe(df, use_container_width=True, hide_index=True)
    else:
        st.caption("No trade zones produced.")

    # --- trade plan -------------------------------------------
    _render_plan(bundle)
    _render_diagnostics(strategy)


def _render_diagnostics(strategy) -> None:
    """Expose the strategy output needed to explain accepted/rejected setups."""
    st.subheader("Strategy Diagnostics")
    zones = getattr(strategy, "zones", []) or []
    tradeable = getattr(strategy, "tradeable", []) or []
    cols = st.columns(3)
    cols[0].metric("Zones evaluated", len(zones))
    cols[1].metric("Tradeable zones (>=70)", len(tradeable))
    cols[2].metric("Rejected / below threshold", len(zones) - len(tradeable))
    if zones:
        st.caption("Each explanation is generated by the strategy engine and records its confluence conditions.")
        st.dataframe(pd.DataFrame([
            {"Score": z.confluence_score, "Tradeable": z.confluence_score >= 70, "Explanation": z.reason}
            for z in zones
        ]), use_container_width=True, hide_index=True)


def _render_plan(bundle: AnalysisBundle) -> None:
    """Render the Week 8 trade plan."""
    plan = bundle.plan
    if plan is None:
        st.info("No trade plan — no setup met the tradeability threshold.")
        return
    st.subheader("Trade Plan")
    cols = st.columns(5)
    cols[0].metric("Direction", plan.direction)
    cols[1].metric("Entry", f"{plan.entry_price:.2f}")
    cols[2].metric("Stop", f"{plan.stop_loss:.2f}")
    cols[3].metric("Target", f"{plan.take_profit:.2f}")
    cols[4].metric("R:R", f"{plan.risk_reward:.2f}")

    ps = getattr(plan, "position_size", None)
    if ps is not None:
        st.caption(f"Volume: {ps.lots} · Risk: ${ps.risk_amount:,.2f}")
    reason = getattr(getattr(bundle.strategy, "decision", None), "reason", "")
    if reason:
        st.write(f"**Reason:** {reason}")


def zones_dataframe(bundle: AnalysisBundle) -> pd.DataFrame:
    """Return the ranked zones as a DataFrame (export helper)."""
    zones = getattr(bundle.strategy, "zones", []) or []
    return pd.DataFrame(
        [
            {
                "direction": str(getattr(z.direction, "value", z.direction)),
                "entry": z.entry_price,
                "stop": z.stop_loss,
                "target": z.target,
                "confluence": z.confluence_score,
                "rr": z.risk_reward_ratio,
                "reason": z.reason,
            }
            for z in zones
        ]
    )


__all__ = ["render", "zones_dataframe"]
